//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praktika123Gai
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string FIO { get; set; }
        public int Tablnomer { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public int age { get; internal set; }
    }
}
